name: Hello World
on: 
  push:
    paths:
      - '.github/workflows/test1.yml'
  workflow_dispatch: #maunual trigger
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: run hello world
      run: echo 'hello world'
    - name: run hello vaibhav
      run: echo 'hello vaibhav'
  second_job:
    runs-on: ubuntu-latest
    steps:
    - name: list directory
      run:  ls -al
    - name: checkout
      uses: actions/checkout@v4
    - name: list directory
      run:  |
        ls
        ls -al
        
  
     
  
  
